###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: optad360-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=optad
        - MYSQL_USER=user
        - MYSQL_PASSWORD=user
      ports:
        - "8003:3306"

    webserver:
      image: nginx:alpine
      container_name: optad360-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8001:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: optad360-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:5.0.1
      restart: always
      environment:
        PMA_HOST: mysql
        PMA_USER: root
        PMA_PASSWORD: secret
      ports:
        - "8080:80"
